version: "3"
services:
    fe1:
      image: selectdb/doris.fe-ubuntu:2.0.2
      hostname: fe1
      environment:
        - FE_SERVERS=fe1:172.25.80.2:9010
        - FE_ID=1
      command: apt install dbus
      entrypoint:
        - /opt/apache-doris/fe/bin/start_fe.sh
      volumes:
        - doris_fe1_data:/opt/apache-doris
      ports:
        - 8030:8030 # HTTP Port
        - 9030:9030 # MySQL Port
      networks:
        doris_net:
          ipv4_address: 172.25.80.2

    be1:
      image: selectdb/doris.be-ubuntu:2.0.2
      hostname: be1
      environment:
        - FE_SERVERS=fe1:172.25.80.2:9010
        - BE_ADDR=172.25.80.3:9050
      entrypoint:
        - /opt/apache-doris/be/bin/start_be.sh
      volumes:
        - doris_be1_data:/opt/apache-doris
      depends_on:
        - fe1
      ports:
        - 9050:9050 # BE Port
        - 8040:8040 # HTTP Port
      networks:
        doris_net:
          ipv4_address: 172.25.80.3

    be2:
      image: selectdb/doris.be-ubuntu:2.0.2
      hostname: be2
      environment:
        - FE_SERVERS=fe1:172.25.80.2:9010
        - BE_ADDR=172.25.80.4:9050
      entrypoint:
        - /opt/apache-doris/be/bin/start_be.sh
      volumes:
        - doris_be2_data:/opt/apache-doris
      depends_on:
        - fe1
      ports:
        - 9051:9050 # BE Port
        - 8041:8040 # HTTP Port
      networks:
        doris_net:
          ipv4_address: 172.25.80.4

networks:
  doris_net:
    ipam:
      config:
        - subnet: 172.25.80.0/24

volumes:
  doris_fe1_data:
  doris_be1_data:
  doris_be2_data: