version: "3"
services:
    fe:
      image: apache/doris:1.2.2-fe-arm
      hostname: fe
      environment:
        - FE_SERVERS=fe1:172.25.80.2:9010
        - FE_ID=1
      volumes:
        - ./data/fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
        - ./data/fe/log/:/opt/apache-doris/fe/log/
      ports:
        - 8030:8030 # HTTP Port
        - 9030:9030 # MySQL Port
      networks:
        doris_net:
          ipv4_address: 172.25.80.2
    be:
      image: apache/doris:1.2.2-be-arm
      hostname: be
      environment:
        - FE_SERVERS=fe1:172.25.80.2:9010
        - BE_ADDR=172.25.80.3:9050
      volumes:
        - ./data/be/storage/:/opt/apache-doris/be/storage/
        - ./data/be/script/:/docker-entrypoint-initdb.d/
      ports:
        - 8040:8040 # HTTP Port
      depends_on:
        - fe
      networks:
        doris_net:
          ipv4_address: 172.25.80.3
networks:
  doris_net:
    ipam:
      config:
        - subnet: 172.25.80.0/16